apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "hench.configSecret" . }}-eso
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hench.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.store.name }}
    kind: {{ .Values.secrets.store.kind }}
  target:
    name: {{ include "hench.configSecret" . }}
    creationPolicy: Owner
  data:
    - secretKey: PLAID_CLIENT_ID
      remoteRef:
        key: {{ .Values.secrets.secretPath }}
        property: {{ .Values.secrets.clientIdKey }}
    - secretKey: PLAID_SECRET
      remoteRef:
        key: {{ .Values.secrets.secretPath }}
        property: {{ .Values.secrets.secretKey }}
    - secretKey: FERNET_KEY
      remoteRef:
        key: {{ .Values.secrets.secretPath }}
        property: {{ .Values.secrets.fernetKey }}
